version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless@3
      - npm install
      - npm install serverless-offline
  build:
    commands:
      - serverless remove
      - serverless deploy
artifacts:
  files:
    - '**/*'