service: user-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true

functions:
  user:
    handler: lambdas/code/user/index.handler
    events:
      - httpApi:
          path: user/create
          method: post
      - httpApi:
          path: user/get
          method: get
      - httpApi:
          path: user/update
          method: put
      - httpApi:
          path: user/delete
          method: delete

plugins:
  - serverless-offline